### ISSUE TITLE
How to use without .env file?

### ISSUE THREAD

**Issue by rigobcastro** [golevelup/ts-ecosystem#1]
Hello @WonderPanda 

What is the best way to use te profiguration without .env file? I mean when the project is developing I can create a .env file locally but when I "dockerize" this is not a god idea build the project with the .env file inside.

Check this https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

I think the `dotenv.config()` is the key.

I hope you can understand me.

**Comment by WonderPanda** [comment]
Hey @rigobcastro all you have to do is include the `env` key when defining your profiguration schema. For example:
```
{
    db: {
      password: {
        default: null,
        format: String,
        env: 'DB_PASSWORD'
      },
      host: {
        url: {
          default: '',
          env: 'DB_HOST_URL'
        },
        port: {
          default: -1,
          format: 'port',
          env: 'DB_HOST_PORT'
        }
      }
    },
  },
```
Here, `DB_PASSWORD`, `DB_HOST_URL` and `DB_HOST_PORT` are all going to be read from process.env

This allows you to set your environment variables properly for production environments. You should not need to include a `.env` file in your deployment.

**Comment by WonderPanda** [comment]
Hi @rigobcastro hopefully this description made sense. I'm going to close this for now feel free to comment or open a new issue if you run into problems or have more questions
