### ISSUE TITLE
Use `dotenv-expand`

### ISSUE THREAD

**Issue by MickL** [golevelup/ts-ecosystem#12]
Would be great to use [dotenv-exapand](https://github.com/motdotla/dotenv-expand) which makes it possible to work with variables in env files:

```
MONGO_PORT=27017
MONGO_URL=mongodb://localhost:${MONGO_PORT}
```

**Comment by underfisk** [comment]
It looks very promising, i don't see any blockers on not having this, @MickL Would you be interested in creating a PR for this?
