### ISSUE TITLE
Why duplicate types with an interface?

### ISSUE THREAD

**Issue by bbangert** [golevelup/ts-ecosystem#4]
A convict Config object will yield the appropriate type with:
```typescript
const configType = ReturnType<Config['getProperties']>
```

Is there some additional reason to manually define an interface for the config? If there is, could the additional type restriction of the interface be merged with the above to reduce duplication?

**Comment by underfisk** [comment]
@bbangert Would you be interested in give more specifics and also having a PR with a proposal for change?
